### ISSUE TITLE
Launching other robots other than default not working

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#144]
When starting the fsw with a robot other than default:
roslaunch astrobee sim.launch rviz:=true gds:=true default:=false honey:=true
You can see by doing "rqt &" on a new command line, that the imu augmentor is publishing the transform from world->body instead of world->honey/body.

This is because the function GetPlatform() is not returning anything because those nodes are not starting the nodelet normally.
The affected nodes are imu_augmentor and graph_localizer, that are not running the functio void FreeFlyerNodelet::onInit() that should be called at startup by the nodelet manager that calls void FreeFlyerNodelet::Setup(ros::NodeHandle & nh, ros::NodeHandle & nh_mt) that define variables like the platform name and node name. 
This bugs affects the simulation only and is critical to the April demo.

**Comment by oleg-alexandrov** [comment]
Hope this is fixed.

BTW, using "default" for the default robot's name is just terribly awkward. The sim.launch and other launch files have default values for variables, like 

arg name="llp" default="local"

and there's the 'default' robot, so text like

arg name="default" default="true"

making the whole thing a pain to understand. At the very least it should be 'default_robot', rather than 'default', or even better, robot_name = "bumble" for the defaut.

Anyhow, not hoping anybody would fix it, but just complaining of poor style.

**Comment by marinagmoreira** [comment]
I'll add this to the fix, I think that's a good point!
