### ISSUE TITLE
Localization Bag Tool Doesn't Use Correct Config

### ISSUE THREAD

**Issue by bcoltin** [nasa/astrobee#208]
Andres will describe the details...

**Comment by amoravargas** [comment]
graph_bag tool requires flag "-f false" to read $HOME/astrobee/astrobee/config/localization.config. Perhaps this could be set by default.

**Comment by rsoussan** [comment]
I'd prefer to leave it as true, as enabling this doesn't just read from the config, but runs optical flow and sparse mapping again using the save image rather than using the save loc/of/features and loc/sparse_mapping/features topics and slows down the graph bag tool a lot (and lowers the frame rate since we only save images at 1/3 rate).  I can improve the documentation though so it's more clear what this option does
