### ISSUE TITLE
Planner might make astrobee stuck

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#216]
Currently the planner and the choreographer check independently for obstacles. The planner checks when the plan is made, and the choreographer checks while the motion is being executed to avoid new obstacles that were not previously mapped.

However, some planners, like the qp planner are more strict on the checks (higher inflation radius), therefore if an obstacle is triggered through the choreographer and a replan action requested, the robot might be unable to plan because it's already too close to the new obstacles.

Choreographer checks: zones + obstacles
QP planned checks: inflate_by_radius(zones + obstacles)

This issue will not show up on the trapezoidal planner

**Comment by trey0** [comment]
I agree that part of the problem is an inconsistency between choreographer and planners. The cleanest way to address that is to first clarify our intended semantics and then make the implementation consistent across all software components (see #207).

However, having consistent semantics would not fully address the problem, because the QP planner optimization will systematically try to skirt as close as possible to prohibited areas, such that any tiny deviation during execution could cause the robot to enter them and get stuck. To avoid that fragile behavior, arguably we would need the QP planner to plan more conservatively. Brian suggested it would be great if the planner could be modified to include an optimization penalty term for trajectories based on how close they get to prohibited areas. If that is a heavy lift because nobody still on the team is fully up to speed on the QP implementation, we could also consider a poor man's approach like invoking the planner multiple times with different safety margins and choosing the resulting plan we like best.

I'm also noticing that if the robot does get stuck in this way, our standing conops is for the operator to use the Settings.setCheckZones or Settings.setCheckObstacles commands [1] to temporarily disable obstacle avoidance, carefully escape the bad state, then restore obstacle avoidance. That is a good reminder to also check that all the necessary software components respect those commands in a consistent way.

[1] https://nasa.github.io/astrobee/html/command_dictionary.html#command_Settings.setCheckObstacles
