### ISSUE TITLE
Docker updates + documentation

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/astrobee#556]
Created this here to deal with docker upgrades

- In one place we recommend "docker exec -it ..." to run an arbitrary command in a container. In other places we recommend "./scripts/docker/run.sh --remote -- cmd ...". Are these different in some useful way (maybe we should explain how) or maybe we should consistently do it the same way in all examples?
- It's not explained that there is a 1-to-1 mapping between the available Dockerfiles and the build.sh targets. (So if you read the description of astrobee_quick and you're interested in using it, you would know to run build.sh astrobee_quick.)
- There isn't an example of how to use build.sh with the astrobee_quick target (like a "lifecycle" of first you build astrobee with this command, then you change something, then you build astrobee_quick with this command so now it's much faster)
- In the unit tests section, there is a discussion of how to use run.sh with --mount and do local build commands within the running container. Is this still a recommended approach or is it somehow redundant with astrobee_quick?

**Comment by trey0** [comment]
- I think we agreed we should recommend to new developers working in software sim that they develop in Ubuntu 20.04 going forward. (The docs have the old recommendation to use 16.04. It's mentioned both in the installation overview and the non-NASA install instructions.)
- We should probably say explicitly that 22.04 is not supported, since at least one new user got confused about it.
- We should replace "the 64-bit version of Ubuntu" with "Ubuntu for amd64 architecture". More places are starting to support arm64 architecture and that could cause confusion.
- For complete novices, perhaps we should say: "There are two main profiles of the Ubuntu distribution, Desktop and Server. Either profile should work for Astrobee development. If you are new to Ubuntu, we recommend that you install the Ubuntu Desktop profile so you can use the full graphical user interface for your development."
- It might help to explain the terms "native build" and "cross-compile" (they appear as section headers, but the meaning might not be obvious). My brief version is: Our development environment is always amd64 architecture. Native build means building for amd64 so you can test in software sim on your development machine. Cross-compile means building for armhf architecture so you can run the code on the robot.
