### ISSUE TITLE
What do I need to know to start contributing with pull requests?

### ISSUE THREAD

**Issue by henriquelimadotcom** [nasa/astrobee#652]
-Would it be a problem to use fedora?
-Where do I send the signed individual contributor license agreement?

**Comment by bcoltin** [comment]
We strongly recommend ubuntu because there are many dependencies and we have set it up to install them all on ubuntu. I expect it would be a lot of work to get the software running on Fedora. We often make use of ubuntu virtual machines and / or docker if that is easier to work with.

Please send the contributor license agreement to the email at the bottom of the page: https://www.nasa.gov/sites/default/files/atoms/files/astrobee_individual_contributor_license_agreement.pdf

Thank you!
