### ISSUE TITLE
Installing on 64-bit Ubuntu 18.04.1 LTS?

### ISSUE THREAD

**Issue by mauricerivers** [nasa/astrobee#8]
Is it possible to install on 64-bit Ubuntu 18.04.1 LTS?
I went through every step, but I get stuck on this step:

`./scripts/configure.sh -l -F -D` 

The output says:

> CMake Error at cmake/FindGlog.cmake:79 (MESSAGE):
>   Failed to find glog - Could not find glog include directory, set
>   GLOG_INCLUDE_DIR to directory containing glog/logging.h
> Call Stack (most recent call first):
>   cmake/FindGlog.cmake:113 (GLOG_REPORT_NOT_FOUND)
>   CMakeLists.txt:162 (find_package)
> 
> -- Configuring incomplete, errors occurred!

Does the installation process get affected because I recently installed ROS (Melodic Morenia)?

Any help is appreciated. Thanks

**Comment by amazinigmech2418** [comment]
It appears that you don't have all libraries required to install the software. If you have the glog library already, try deleting it and re-downloading the library and make sure that the library is in a directory containing glog/logging.h. If it doesn't contain that, you may have to rename at least one directory or even repackage the library to work with the software. However, since the code required for the library would already be in the package, it should be easy to repackage if required.

**Comment by bcoltin** [comment]
We currently only support ROS kinetic.
